### ISSUE TITLE
redefine BracesForIfElse rule

### ISSUE THREAD

**Issue by ppazos** [nvuillam/npm-groovy-lint#43]
I'm trying to redefine the BracesForIfElse since I use braces on different lines for readability.

The documentation says to create a file, doesn't say were. A step by step process would be nice for being able to adapt the extension rules to our dev process.

Thanks.

**Comment by nvuillam** [comment]
Updated documentation :)
![image](https://user-images.githubusercontent.com/17500430/81917651-c2620d80-95d5-11ea-8657-efcd9ea7f86a.png)

About [BracesForIfElse](https://codenarc.github.io/CodeNarc/codenarc-rules-formatting.html#bracesforifelse-rule), you can override the default definition ( sameLine: true ) with sameLine: false ), but it will be taken in account only for linting , because today the formatting/fix rules only manage the default rules definitions ( this is a quite new package, if you want to contribute you are welcome :) )

Example:

- your-repo-root-folder
  - src
     - groovy
       - mygroovyfile.groovy
  - Jenkinsfile
  - .groovylintrc.json _(do not forget the dot at the beginning of the file name)_

**.groovylintrc.json** content : 
```json
{
    "extends": "recommended",
    "rules": {
        "BracesForIfElse": {
            "sameLine": false,
            "severity": "info"
        }
    }
}
```

**Comment by ppazos** [comment]
@nvuillam thanks for the info!
